version: '3'
name: autoqa
services:
  traefik:
    image: traefik:v2.5
    command:
     
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8989"
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.watch=true"
      - "--accesslog=true"
      - "--log.level=INFO"
      - "--log.filePath=/var/log/traefik.log"
      - "--log"
    ports:
      - "8989:8989"
      - "8080:8080" # Traefik Dashboard (optional)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - autoqa_network

  api-upload-report-service:
    image: bruceycyang/ui-upload-api:v0.0.5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-upload-report.rule=PathPrefix(`/api-upload`)"
      - "traefik.http.middlewares.api-upload-report-stripprefix.stripprefix.prefixes=/api-upload"
      - "traefik.http.routers.api-upload-report.middlewares=api-upload-report-stripprefix"
      - "traefik.http.routers.api-upload-report.entrypoints=web"
      - "traefik.http.services.api-upload-report.loadbalancer.server.port=8787"
    networks:
      - autoqa_network

networks:
  autoqa_network:
    driver: bridge